### PR TITLE
Pure JavaScript implementation of crc32

### PR DESCRIPTION
**Pull request by horejsek**
I switched to pure JavaScript implementation as we discussed in https://github.com/Touffy/client-zip/issues/49. I didn't remove wasm version because I think you will use it for the faster version? I also didn't modify README for the same reason and also because I don't have the setup you used for benchmarks. I did some benchmarks myself, and I found it the same performance or even faster, so I would be curious to see what you can measure. It seems to work just fine. Let me know what you want me to provide together with this PR.

### CODE REVIEW

**Comment by Touffy** [comment]
My setup changed since I last ran the benchmarks anyway, I'll have to do them all over again on my M1. And I'll have to test the SIMD-enabled variant again too.

The faster WASM version doesn't really change the current WASM implementation (you can see in my PR, it has zero changes to that file), it just reused its memory and the table in it inside a new and independent WASM module. I tried doing something "smart" where the faster module would reuse the current module, but it didn't pan out.

**Comment by horejsek** [comment]
Have you had time to check the performance; is it also same or faster for you?

**Comment by horejsek** [comment]
Hello, do you have any update for this one? :-)

**Comment by Touffy** [comment]
Hey. Sorry I left this for so long, but I finally updated my performance tests and ran them with your branch. It turns out that my old WASM implementation is now slower than pure JS ! Merging this now.

**Pull request merged**
